# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            displayName: 'Build and Push Docker Image'
            inputs:
              containerRegistry: 'acr-connection'
              repository: 'papanol'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
  - stage: Deploy
    jobs:
      - deployment: Deploy
        environment: 'AzureWebApp'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebAppContainer@1
                  inputs:
                    azureSubscription: 'arm-connection'
                    appName: 'lampteywebapp'
                    containerRegistry: 'lampteydccloudregistry.azurecr.io'
                    imageName: 'lampteydccloudregistry:$(Build.BuildId)'
