trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Docker Build and Push
        steps:
          # Checkout the repository
          - task: Checkout@1

          # Build and Push Docker Image to ACR
          - task: Docker@2
            displayName: 'Build and Push Docker Image to ACR'
            inputs:
              containerRegistry: 'acr-connection'          # Docker Registry service connection
              repository: 'papanol'                       # Repository name in your ACR
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'                 # Path to Dockerfile
              tags: |
                $(Build.BuildId)                          # Use build ID as the tag

  - stage: Deploy
    displayName: Deploy to Azure App Service
    jobs:
      - deployment: Deploy
        displayName: Deploy to Azure Web App
        environment: 'AzureWebApp'
        strategy:
          runOnce:
            deploy:
              steps:
                # Deploy the Docker image to Azure Web App
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Docker Image to Azure Web App'
                  inputs:
                    azureSubscription: 'arm-connection'               # Azure Resource Manager service connection
                    appName: 'lampteywebapp'                          # Name of the Azure App Service
                    containerRegistry: 'lampteydccloudregistry.azurecr.io' # ACR Login Server
                    imageName: 'papanol:$(Build.BuildId)'             # Repository and tag for the Docker image
