trigger:
  - main

pool:
  name: pipeline-pool  # Use the self-hosted agent pool
  demands:
    - agent.name -equals niipapa-VirtualBox  # Use the specific self-hosted agent

jobs:
  - job: BuildAndDeploy
    displayName: Build and Deploy
    steps:
      # Checkout the repository
      - checkout: self
        displayName: 'Checkout Source Code'

      # Build and Push Docker Image to Azure Container Registry
      - task: Docker@2
        displayName: 'Build and Push Docker Image'
        inputs:
          containerRegistry: 'acr-service-connection'  # Azure service connection for ACR
          repository: 'papadhruvacr/appweb'            # Repository name in your ACR
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(Build.BuildId)

      # Deploy Docker Image to Azure App Service
      - task: AzureWebAppContainer@1
        displayName: 'Deploy Docker Image to Azure Web App'
        inputs:
          azureSubscription: 'azure-arm-connection'  # Azure ARM service connection
          appName: 'appweb'                          # Azure App Service name
          containerRegistry: 'papadhruvacr.azurecr.io'  # ACR login server
          imageName: 'papadhruvacr/appweb:$(Build.BuildId)'  # Docker image with tag
