trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: lampteywebapp
      type: github
      name: papanol/lampteywebapp
      endpoint: github.com_papanol

stages:
  # Build Stage
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Docker Build and Push
        steps:
          # Checkout the external GitHub repository
          - checkout: lampteywebapp
            displayName: 'Checkout GitHub Repository'

          # Build and Push Docker Image to ACR
          - task: Docker@2
            displayName: 'Build and Push Docker Image to ACR'
            inputs:
              containerRegistry: 'arc-connection'           # ACR service connection
              repository: 'lampteydccloudregistry'         # ACR repository name
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'                  # Path to Dockerfile in the repository
              tags: |
                $(Build.BuildId)                           # Use Build ID as the tag

  # Deploy Stage
  - stage: Deploy
    displayName: Deploy to Azure App Service
    jobs:
      - deployment: Deploy
        displayName: Deploy to Azure Web App
        environment: 'AzureWebApp'
        strategy:
          runOnce:
            deploy:
              steps:
                # Deploy the Docker image to Azure Web App
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Docker Image to Azure Web App'
                  inputs:
                    azureSubscription: 'arm-connection'                 # ARM service connection
                    appName: 'lampteywebapp'                            # Azure Web App name
                    containerRegistry: 'lampteydccloudregistry.azurecr.io' # ACR login server
                    imageName: 'lampteydccloudregistry:$(Build.BuildId)' # Image name with tag
