trigger:
  - main

pool:
  name: lamptey  # Reference the agent pool with one agent

resources:
  repositories:
    - repository: lampteywebapp
      type: github
      name: papanol/lampteywebapp
      endpoint: github.com_papanol

stages:
  # Build Stage
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Docker Build and Push
        steps:
          # Checkout the external GitHub repository
          - checkout: lampteywebapp
            displayName: 'Checkout GitHub Repository'

          # Build and Push Docker Image to ACR
          - task: Docker@2
            displayName: 'Build and Push Docker Image to ACR'
            inputs:
              containerRegistry: 'acr-connection'
              repository: 'lampteydccloudregistry'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)

  # Deploy Stage
  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: Build  # Ensure Deploy stage only runs after Build
    jobs:
      - deployment: Deploy
        displayName: Deploy to Azure Web App
        environment: 'AzureWebApp'
        strategy:
          runOnce:
            deploy:
              steps:
                # Deploy the Docker image to Azure Web App
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Docker Image to Azure Web App'
                  inputs:
                    azureSubscription: 'arm-connection'
                    appName: 'lampteywebapp'
                    containerRegistry: 'lampteydccloudregistry.azurecr.io'
                    imageName: 'lampteydccloudregistry:$(Build.BuildId)'
