trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: self

variables:
  # Docker registry service connection
  dockerRegistryServiceConnection: 'a5ad5cb3-4c85-41f1-aeee-8bd7a9f66ba5' # Update with your service connection ID
  imageRepository: 'lampteydccloudregistry'
  containerRegistry: 'lampteydccloudregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile' # Path to Dockerfile in the root
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Build and Push
        pool:
          vmImage: $(vmImageName)
        steps:
          # Checkout the code repository
          - checkout: self
            displayName: 'Checkout Code'

          # Build and Push the Docker Image
          - task: Docker@2
            displayName: 'Build and Push Image to ACR'
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
