trigger:
  - main

pool:
  name: lamptey  # Ensure this is the name of the agent pool in Azure DevOps
  demands:
    - agent.name -equals lampteyagent1  # Specify the Linux agent name

resources:
  repositories:
    - repository: lampteywebapp
      type: github
      name: papanol/lampteywebapp
      endpoint: github.com_papanol  # Ensure the service connection exists

stages:
  # Build Stage
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Docker Build and Push
        pool:
          name: lamptey
          demands:
            - agent.name -equals lampteyagent1
        steps:
          # Checkout the external GitHub repository
          - checkout: lampteywebapp
            displayName: 'Checkout GitHub Repository'

          # Build and Push Docker Image to ACR
          - task: Docker@2
            displayName: 'Build and Push Docker Image to ACR'
            inputs:
              containerRegistry: 'acr-connection'
              repository: 'lampteyacr'  # Updated ACR repository name
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)

  # Deploy Stage
  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: Deploy to Azure Web App
        environment: 'AzureWebApp'
        pool:
          name: lamptey
          demands:
            - agent.name -equals lampteyagent1
        strategy:
          runOnce:
            deploy:
              steps:
                # Deploy the Docker image to Azure Web App
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Docker Image to Azure Web App'
                  inputs:
                    azureSubscription: 'arm-connection'
                    appName: 'lampteywebapp'
                    containerRegistry: 'lampteyacr.azurecr.io'  # Updated ACR login server
                    imageName: 'lampteyacr:$(Build.BuildId)'  # Updated ACR name with tag
