trigger:
  - main

pool:
  name: lampteypool   # Specify the agent pool
  demands:
    - Agent.Name -equals PAPA  # Ensure the pipeline uses the PAPA agent

variables:
  # Docker registry service connection
  dockerRegistryServiceConnection: 'a5ad5cb3-4c85-41f1-aeee-8bd7a9f66ba5' # Replace with your service connection ID
  imageRepository: 'lampteydccloudregistry'
  containerRegistry: 'lampteydccloudregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Build
        steps:
          # Checkout code repository
          - checkout: self
            displayName: 'Checkout Code'

          # List files in the repository for debugging
          - script: ls -R $(Build.SourcesDirectory)
            displayName: 'List Repository Contents'

          # Build and Push Docker Image
          - task: Docker@2
            displayName: 'Build and Push Docker Image to ACR'
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
