trigger:
  - main

pool:
  name: pipeline-pool  # Use the self-hosted agent pool

stages:
  # Build Stage
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Build Docker Image and Push to ACR
        pool:
          name: pipeline-pool
        steps:
          # Checkout the repository
          - checkout: self
            displayName: 'Checkout Source Code'

          # Build and Push Docker Image to Azure Container Registry
          - task: Docker@2
            displayName: 'Build and Push Docker Image'
            inputs:
              containerRegistry: 'acr-service-connection'  # Azure service connection for ACR
              repository: 'papadhruvacr/appweb'            # Repository name in your ACR
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)

  # Deploy Stage
  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: Deploy to Azure Web App
        environment: 'AzureWebApp'
        pool:
          name: pipeline-pool
        strategy:
          runOnce:
            deploy:
              steps:
                # Deploy Docker Image to Azure Web App
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Docker Image to Azure Web App'
                  inputs:
                    azureSubscription: 'azure-arm-connection'  # Azure ARM service connection name
                    appName: 'appweb'                          # Azure App Service name
                    containerRegistry: 'papadhruvacr.azurecr.io'  # ACR login server
                    imageName: 'papadhruvacr/appweb:$(Build.BuildId)'  # Docker image with tag
